name: 'Gluon Build License'
description: 'Action to configure your Gluon license.'
branding:
  icon: check-square
  color: blue
inputs:
  gluon-license:
    required: true
    description: License provided by Gluon
  dir:
    required: false
    description: Directory path to Gluon Application. Useful in multi-module project setup.
runs:
  using: "composite"
  steps: 
    - run: printf "${{ inputs.gluon-license }}" > "${{ inputs.dir }}"/src/main/resources/gluonmobile.license
      shell: bash
